### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by PDL2CGamejolt** [DatGamerYoloYT/The-2012-Internet#1]
can i contribute to this

**Comment by DatGamerYoloYT** [comment]
no.

**Comment by PDL2CGamejolt** [comment]
y

**Comment by DatGamerYoloYT** [comment]
you do realize I'm still not ready to unblock you on gamejolt yet?

If you want me to unblock you, then just contact me on a site that we both are on saying that you are sorry for being annoying.

If you do that then I'll think if I should unblock you.

**Comment by PDL2CGamejolt** [comment]
Ill just wait.
